// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../../components/plasmic/style_in_form/PlasmicGlobalContextsProvider";
import { ScreenVariantProvider } from "../../components/plasmic/style_in_form/PlasmicGlobalVariant__Screen";
import { PlasmicItem } from "../../components/plasmic/style_in_form/PlasmicItem";
import { useRouter } from "next/router";
import { medusaClient } from "@/lib/config";
import { GetStaticProps, GetStaticPropsContext } from "next";
import { extractPlasmicQueryData } from "@plasmicapp/react-web/lib/prepass";
import { PlasmicQueryDataProvider } from "@plasmicapp/react-web/lib/query";

interface ItemPageProps {
  queryCache: Record<string, any>;
}

function Item(props: ItemPageProps) {
  // Use PlasmicItem to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicItem are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicItem is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <PlasmicQueryDataProvider prefetchedCache={props.queryCache}>
      <GlobalContextsProvider>
        <PageParamsProvider__
          route={useRouter()?.pathname}
          params={useRouter()?.query}
          query={useRouter()?.query}
        >
          <PlasmicItem />
        </PageParamsProvider__>
      </GlobalContextsProvider>
    </PlasmicQueryDataProvider>
  );
}

export const getStaticPaths = (async () => {
  const products = (await medusaClient.products.list()).products;
  return {
    paths: products.map(product => (
      {
        params: {
          handle: product.handle ?? product.id
        },
      }
    )),
    fallback: true,
  }
}) 

export const getStaticProps: GetStaticProps = async (context) => {
  // Cache the necessary data fetched for the page
  const queryCache = await extractPlasmicQueryData(
    <PageParamsProvider__
      params={context.params}
    >
      <PlasmicItem />
    </PageParamsProvider__>
  );
  // Use revalidate if you want incremental static regeneration
  return { props: { queryCache }, revalidate: 60 };
}
export default Item;
